### ISSUE TITLE
Small bug in No Object Contain Loss

### ISSUE THREAD

**Issue by cjl99** [Liang-ZX/HKU-DASC7606-A1#1]
In `loss.py`, For supporting multiple choices of **yolo_B**, 4th Term (Part II): **No Object Contain Loss** should be
```
for i in range(self.B):
    noo_pred_mask[:, i*5+4] = 1
```
instead of 
```
noo_pred_mask[:, 4] = 1
noo_pred_mask[:, 9] = 1
```

**Comment by Liang-ZX** [comment]
> In `loss.py`, For supporting multiple choices of **yolo_B**, 4th Term (Part II): **No Object Contain Loss** should be
> 
> ```
> for i in range(self.B):
>     noo_pred_mask[:, i*5+4] = 1
> ```
> 
> instead of
> 
> ```
> noo_pred_mask[:, 4] = 1
> noo_pred_mask[:, 9] = 1
> ```

Yes, you are right. Thank you.
